# Generated by Django 4.1.3 on 2023-01-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0002_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
