# Generated by Django 4.1.3 on 2023-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
