# Generated by Django 4.1.3 on 2023-01-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0005_alter_order_ordered_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together={('order', 'product')},
        ),
    ]
