# Generated by Django 4.1.3 on 2023-01-21 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='bangazonapi.category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.user'),
        ),
    ]
