# Generated by Django 4.1.3 on 2023-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
