# Generated by Django 4.1.3 on 2023-02-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0012_alter_productorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('canceled', 'Canceled')], default='in-progress', max_length=20),
        ),
    ]
